[platformio]
default_envs = xiao_control

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_LOOP_STACK_SIZE=16384
  -DBNO_ROTATION_VECTOR_DIRECT=1
lib_deps =
  adafruit/Adafruit BNO08x @ 1.2.5
  adafruit/Adafruit BusIO @ 1.17.4
  sparkfun/SparkFun VL53L5CX Arduino Library

[env:xiao_control]
build_flags =
  ${env.build_flags}
  -DBOAT_DRY_RUN=0

[env:xiao_control_dry_run]
build_flags =
  ${env.build_flags}
  -DBOAT_DRY_RUN=1
