[platformio]
default_envs = xiao_communication

[env:xiao_communication]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_LOOP_STACK_SIZE=16384
